In [20]:
from sklearn import datasets
cancer = datasets.load_breast_cancer()
import numpy as np

In [21]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, Y_train, Y_test = tts(cancer.data, cancer.target, test_size=0.2)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
clf = KNeighborsClassifier(n_neighbors=9)
clf.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=9, p=2,
           weights='uniform')

In [24]:
clf.score(X_test, Y_test)
X_train
Y_test

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1])

In [25]:
def predictMe(train, test, labels, neighbors):
    
    import numpy as np
    distances = []
    for i in range(len(test)):
        for j in range(len(train)):
            distances.append([])
            distances[j].append(np.sqrt(np.sum((train[j]-test[i])**2)))
            distances[j].append(labels[j])
    
    a = np.array(distances, dtype=int)
    a = a[a[:,0].argsort()]
    a = a[:neighbors]
    
    
    (values,counts) = np.unique(a,return_counts=True)
    ind=np.argmax(counts)
    return values[ind] 

In [26]:
a = np.array([predictMe(X_train, X_test[i:i+1], Y_train, 20) for i in range(len(X_test))])
a

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1])

In [27]:
a - Y_test

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0])

In [28]:
def cross_entropy(predictions, targets, epsilon=1e-12):
    """
    Computes cross entropy between targets (encoded as one-hot vectors)
    and predictions. 
    Input: predictions (N, k) ndarray
           targets (N, k) ndarray        
    Returns: scalar
    """
    predictions = np.clip(predictions, epsilon, 1. - epsilon)
    N = predictions.shape[0]
    ce = -np.sum(np.sum(targets*np.log(predictions+1e-9)))/N
    return ce

In [29]:
cross_entropy(a, Y_test)

0.545322797692219

In [30]:
from sklearn.metrics import classification_report
print (classification_report(Y_test, a))

             precision    recall  f1-score   support

          0       0.91      0.84      0.88        38
          1       0.92      0.96      0.94        76

avg / total       0.92      0.92      0.92       114

