In [3]:
from sklearn import datasets

iris_data = datasets.load_iris() #import iris dataset

In [4]:
import pandas as pd

iris = pd.DataFrame(iris_data.data) #convert iris data into dataframe

In [5]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.columns = iris_data.feature_names #give column names to iris data

In [7]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
iris_data.target #get labels for the dataset

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn import cross_validation as cv  #separate data into test and train
X_train, X_test, Y_train, Y_test = cv.train_test_split(iris, iris_data.target, test_size=0.2)

/home/kautuk/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()  #create classifier

In [11]:
clf.fit(X_train, Y_train)  #fit the data into the classifier

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
clf.score(X_test, Y_test) #accuacy score when considering this as regression

0.90659289470780513

In [13]:
prediction = clf.predict(X_test)
prediction

array([ 1.98792685,  1.89252771,  1.72702213,  0.03224198,  1.44725199,
        1.39673337,  0.01465131,  1.29501337,  0.22380897, -0.01789059,
        1.22675772,  1.69913   ,  2.05562364,  1.63881897,  1.1898955 ,
        0.88511228,  1.77789366,  0.01795305,  1.55765556,  1.25205043,
       -0.14938325,  1.07263857,  1.04122168,  0.09509923, -0.0903304 ,
        1.32710283,  1.95748162,  1.73316978,  1.43571911,  1.86823012])

In [14]:
import numpy as np

In [15]:
np.shape(prediction)

(30,)

In [16]:
prediction = np.rint(prediction)
prediction

array([ 2.,  2.,  2.,  0.,  1.,  1.,  0.,  1.,  0., -0.,  1.,  2.,  2.,
        2.,  1.,  1.,  2.,  0.,  2.,  1., -0.,  1.,  1.,  0., -0.,  1.,
        2.,  2.,  1.,  2.])

In [25]:
from sklearn.metrics import classification_report

In [26]:
report = classification_report(Y_test, prediction, target_names=iris_data.target_names)
report

'             precision    recall  f1-score   support\n\n     setosa       1.00      1.00      1.00         8\n versicolor       0.82      1.00      0.90         9\n  virginica       1.00      0.85      0.92        13\n\navg / total       0.95      0.93      0.93        30\n'