In [1]:
from sklearn import datasets

iris_data = datasets.load_iris() #import iris dataset

In [2]:
import pandas as pd

iris = pd.DataFrame(iris_data.data) #convert iris data into dataframe

In [3]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.columns = iris_data.feature_names #give column names to iris data

In [5]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
iris_data.target #get labels for the dataset

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [213]:
from sklearn import cross_validation as cv  #separate data into test and train
X_train, X_test, Y_train, Y_test = cv.train_test_split(iris, iris_data.target, test_size=0.9)

In [214]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(100,), activation='logistic', max_iter=2000) #create classifier

In [215]:
clf.fit(X_train, Y_train)  #fit the data into the classifier

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [216]:
clf.score(X_test, Y_test) #accuacy score when considering this as regression

0.9555555555555556

In [156]:
prediction = clf.predict(X_test)
prediction

array([0, 1, 1, 2, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2,
       2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 2, 1, 2, 1, 0, 2, 1, 2,
       1, 2, 0, 2, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 1, 0,
       0, 1, 1, 2, 1, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 1, 1, 0, 0, 2, 2, 0,
       2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 1, 2, 0, 0, 0, 2, 1, 2, 0, 0, 2,
       1, 0, 2, 1, 0, 2, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 0,
       2, 1, 0])

In [140]:
import numpy as np

In [141]:
np.shape(prediction)

(30,)

In [142]:
prediction = np.rint(prediction)
prediction

array([0., 2., 1., 2., 0., 0., 0., 2., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 2., 1., 2., 2., 2., 1., 2., 0., 2., 2., 1.])

In [143]:
from sklearn.metrics import classification_report

In [144]:
report = classification_report(Y_test, prediction, target_names=iris_data.target_names)
print(report)

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        10
 versicolor       1.00      1.00      1.00        10
  virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

