In [20]:
import numpy as np

In [21]:
def sig(z):
    return 1/(1 + np.exp(-z))

def der_sig(sig_out):
    return sig_out*(1-sig_out)

In [67]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
Y = np.array([[1,0,0,1]]).T

In [43]:
np.random.seed(0)
weights = 2 * np.random.random((3,1)) - 1
print(weights)

[[0.09762701]
 [0.43037873]
 [0.20552675]]


In [45]:
for iter in range(10000):
    rate = 0.1

    output0 = X
    output1 = sig(np.dot(output0, weights))

    first_term = output1 - Y
    second_term = der_sig(output1)
    first_two = first_term * second_term
    third_term = output0

    changes = np.array([[0.,0.,0.]])

    for i in range(3):
        for j in range(4):
            changes[0][i] = changes[0][i] + first_two[j][0]*output0[j][i]
    
    weights = weights - rate*changes.T

output1 = sig(np.dot(X, weights))
print(np.round(output1,2))

[[0.03]
 [0.02]
 [0.98]
 [0.98]]


In [68]:
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2*np.random.random((4,1)) - 1

In [70]:
for iter in range(100000):
    layer0 = X
    layer1 = sig(np.dot(layer0, weights0))
    layer2 = sig(np.dot(layer1, weights1))

    l2_error = layer2 - Y
    l2_delta = l2_error * der_sig(layer2)

    net_change2 = np.dot(layer1.T, l2_delta)

    l1_error = l2_delta.dot(weights1.T)
    l1_delta = l1_error * der_sig(layer1)

    net_change1 = np.dot(layer0.T, l1_delta)

    weights0 = weights0 - rate*net_change1
    weights1 = weights1 - rate*net_change2

layer0 = X
layer1 = sig(np.dot(layer0, weights0))
layer2 = sig(np.dot(layer1, weights1))
np.round(layer2,3)

array([[0.99 ],
       [0.01 ],
       [0.008],
       [0.991]])