In [5]:
import numpy as np
l = [2,3,4]
np.array(l)

array([2, 3, 4])

In [11]:
b = np.zeros(5,  int)
b

array([0, 0, 0, 0, 0])

In [12]:
c = np.zeros((4,5), int)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
c[0][1] = 1
c

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
# operations on NP array

#elementwise add

a = np.array([2,3])
b = np.array([1,2])
a+b

array([3, 5])

In [19]:
a*b

array([2, 6])

In [20]:
a**b

array([2, 9])

In [21]:
a.mean()

2.5

In [28]:
b2 = np.array([[1,2],[5,3]])
b2.shape

(2, 2)

In [50]:
#print row

print(b2[0])

[1 2]


In [49]:
#print column

print(b2[:, 0])

[1 5]


In [34]:
#get sub array

t = np.array([[1,2,3],[4,5,6],[7,8,9]])

print (t[1:3, 1:3])

[[5 6]
 [8 9]]


In [35]:
#dot product

a = np.array([1,2])
b = np.array([3,4])

a.dot(b)

11

In [40]:
# 2x2 dot 2x3

a = np.array([[1,2],[2,3]])
b = np.array([[1,2,3],[4,5,6]])

a.dot(b)

array([[ 9, 12, 15],
       [14, 19, 24]])

In [41]:
#distance between points

a = np.array([1,2,3])
b = np.array([1,2,5])

((a-b)**2).sum()

4

In [47]:
#variance

a = np.array([1,2,3,4,5])

print (((a-a.mean())**2).mean())

a.var()  #inbuilt function of variance


2.0


2.0