In [2]:
import tensorflow as tf

In [3]:
a = tf.constant([2])
b = tf.constant([3])

c = tf.add(a,b)

with tf.Session() as sess:
    print (sess.run(c))

[5]


In [6]:
a = tf.constant([[1,2],[4,5]])
b = tf.constant([[4,5],[6,7]])

c = tf.add(a,b)
d = tf.multiply(a,b)
e = tf.matmul(a,b)

with tf.Session() as sess:
    print(sess.run(c))
    print(sess.run(d))    
    print(sess.run(e))    

[[ 5  7]
 [10 12]]
[[ 4 10]
 [24 35]]
[[16 19]
 [46 55]]


In [11]:
count = tf.Variable(0)
increment = tf.add(count, 1)
update = tf.assign(count, increment)

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    for i in range(5):
        print(sess.run(update))

1
2
3
4
5


In [12]:
test = tf.Variable(0)
assignment = tf.assign(test, 45)

with tf.Session() as sess:
    sess.run(assignment)
    print(sess.run(test))

45
